import { ref, Ref } from 'vue'
import ITask from '@/interfaces/ITask'

class ApiService {
    private tasks:Ref<Array<ITask>>

    constructor(){
        this.tasks = ref<Array<ITask>>([])
    }

    getTasks():Ref<Array<ITask>>{
        return this.tasks
    }

    async fetchTasksOffline():Promise<void>{
        const responseStringVUI = `[
            {
                "TaskId": 946781,
                "ProcessId": 13839,
                "StatusName": "Llegada",
                "ProcessClassName": "Solicitud de Ingreso al Régimen de Zonas Francas",
                "ProcessBaseReference": "VUI-2.1_1148",
                "ProcessTheme1": "FINCA ISLA DE LOS NEGRITOS SOCIEDAD ANONIMA",
                "ProcessTheme2": "Administradora",
                "ProcessTheme3": "Dentro del G.A.M",
                "ProcessTheme4": "28/01/2023",
                "ProcessTheme5": "",
                "ProcessTheme6": "",
                "ProcessTheme7": "",
                "ProcessTheme8": "",
                "ProcessTheme9": "",
                "ProcessTheme10": "",
                "TaskClassCode": "TP.64",
                "TaskClassName": "Revisar requisitos que deben cumplir para la autorización ACFPA",
                "ArrivalDate": "2022-11-01T11:03:26.373-06:00",
                "Deadline": "2024-11-01T11:03:26.373-06:00",
                "NoticeDate": "1900-01-01T00:00:00",
                "OriginalStartDatePrevision": "1900-01-01T00:00:00",
                "OriginalEndDatePrevision": "1900-01-01T00:00:00",
                "CurrentStartDatePrevision": "1900-01-01T00:00:00",
                "CurrentEndDatePrevision": "1900-01-01T00:00:00",
                "NameOfStartMessageCreator": "ApExt",
                "NatureOfStartMessageCreator": "Externo",
                "IsReclaimable": true,
                "Project": "VUI"
              },
              {
                "TaskId": 946788,
                "ProcessId": 13757,
                "StatusName": "Llegada",
                "ProcessClassName": "Solicitud de Ingreso al Régimen de Zonas Francas",
                "ProcessBaseReference": "VUI-2.1_1139",
                "ProcessTheme1": "CIELO DIGITAL SOCIEDAD DE RESPONSABILIDAD LIMITADA",
                "ProcessTheme2": "Administradora",
                "ProcessTheme3": "Dentro del G.A.M",
                "ProcessTheme4": "10/08/2023",
                "ProcessTheme5": "",
                "ProcessTheme6": "",
                "ProcessTheme7": "",
                "ProcessTheme8": "",
                "ProcessTheme9": "",
                "ProcessTheme10": "",
                "TaskClassCode": "TP.64",
                "TaskClassName": "Revisar requisitos que deben cumplir para la autorización ACFPA",
                "ArrivalDate": "2022-11-01T11:42:13.223-06:00",
                "Deadline": "2024-11-01T11:42:13.223-06:00",
                "NoticeDate": "1900-01-01T00:00:00",
                "OriginalStartDatePrevision": "1900-01-01T00:00:00",
                "OriginalEndDatePrevision": "1900-01-01T00:00:00",
                "CurrentStartDatePrevision": "1900-01-01T00:00:00",
                "CurrentEndDatePrevision": "1900-01-01T00:00:00",
                "NameOfStartMessageCreator": "WENDY TATIANA MORA PEREZ",
                "NatureOfStartMessageCreator": "Externo",
                "IsReclaimable": true,
                "Project": "VUI"
              },
              {
                "TaskId": 946850,
                "ProcessId": 13839,
                "StatusName": "Iniciada",
                "ProcessClassName": "Solicitud de Ingreso al Régimen de Zonas Francas",
                "ProcessBaseReference": "VUI-2.1_1148",
                "ProcessTheme1": "FINCA ISLA DE LOS NEGRITOS SOCIEDAD ANONIMA",
                "ProcessTheme2": "Administradora",
                "ProcessTheme3": "Dentro del G.A.M",
                "ProcessTheme4": "28/01/2023",
                "ProcessTheme5": "",
                "ProcessTheme6": "",
                "ProcessTheme7": "",
                "ProcessTheme8": "",
                "ProcessTheme9": "",
                "ProcessTheme10": "",
                "TaskClassCode": "TP.110",
                "TaskClassName": "Generar Acuerdo Ejecutivo de Revocatoria",
                "ArrivalDate": "2022-11-03T18:09:57.227-06:00",
                "Deadline": "1900-01-01T00:00:00",
                "NoticeDate": "1900-01-01T00:00:00",
                "OriginalStartDatePrevision": "1900-01-01T00:00:00",
                "OriginalEndDatePrevision": "1900-01-01T00:00:00",
                "CurrentStartDatePrevision": "1900-01-01T00:00:00",
                "CurrentEndDatePrevision": "1900-01-01T00:00:00",
                "NameOfStartMessageCreator": "ApExt",
                "NatureOfStartMessageCreator": "Externo",
                "IsReclaimable": false,
                "Project": "VUI"
              },
              {
                "TaskId": 948922,
                "ProcessId": 14457,
                "StatusName": "Iniciada",
                "ProcessClassName": "Solicitud de Ingreso al Régimen de Zonas Francas",
                "ProcessBaseReference": "VUI-2.1_1177",
                "ProcessTheme1": "WALMART GSS LATIN AMERICA SOCIEDAD DE RESPONSABILIDAD LIMITADA",
                "ProcessTheme2": "Administradora.",
                "ProcessTheme3": "Dentro del G.A.M",
                "ProcessTheme4": "26/01/2023",
                "ProcessTheme5": "",
                "ProcessTheme6": "",
                "ProcessTheme7": "",
                "ProcessTheme8": "",
                "ProcessTheme9": "",
                "ProcessTheme10": "",
                "TaskClassCode": "TP.26",
                "TaskClassName": "Análisis del Acuerdo Ejecutivo abogado Leyes y Decretos",
                "ArrivalDate": "2022-11-29T16:09:12.137-06:00",
                "Deadline": "1900-01-01T00:00:00",
                "NoticeDate": "1900-01-01T00:00:00",
                "OriginalStartDatePrevision": "1900-01-01T00:00:00",
                "OriginalEndDatePrevision": "1900-01-01T00:00:00",
                "CurrentStartDatePrevision": "1900-01-01T00:00:00",
                "CurrentEndDatePrevision": "1900-01-01T00:00:00",
                "NameOfStartMessageCreator": "ApExt",
                "NatureOfStartMessageCreator": "Externo",
                "IsReclaimable": false,
                "Project": "VUI"
              },
              {
                "TaskId": 952474,
                "ProcessId": 14354,
                "StatusName": "Iniciada",
                "ProcessClassName": "Solicitud de Ingreso al Régimen de Zonas Francas",
                "ProcessBaseReference": "VUI-2.1_1174",
                "ProcessTheme1": "FINCA ISLA DE LOS NEGRITOS SOCIEDAD ANONIMA",
                "ProcessTheme2": "Procesadora, Servicios y Comercializadora",
                "ProcessTheme3": "Dentro del G.A.M",
                "ProcessTheme4": "01/01/2023",
                "ProcessTheme5": "",
                "ProcessTheme6": "",
                "ProcessTheme7": "",
                "ProcessTheme8": "",
                "ProcessTheme9": "",
                "ProcessTheme10": "",
                "TaskClassCode": "TP.118",
                "TaskClassName": "Análisis y generación de Documentación ANALISTAS",
                "ArrivalDate": "2023-02-28T15:52:39.947-06:00",
                "Deadline": "1900-01-01T00:00:00",
                "NoticeDate": "1900-01-01T00:00:00",
                "OriginalStartDatePrevision": "1900-01-01T00:00:00",
                "OriginalEndDatePrevision": "1900-01-01T00:00:00",
                "CurrentStartDatePrevision": "1900-01-01T00:00:00",
                "CurrentEndDatePrevision": "1900-01-01T00:00:00",
                "NameOfStartMessageCreator": "ApExt",
                "NatureOfStartMessageCreator": "Externo",
                "IsReclaimable": false,
                "Project": "VUI"
              }
         ]`

         const responseStringPROCOMER = `[
            {
                "TaskId": 1573,
                "ProcessId": 3330,
                "StatusName": "Iniciada",
                "ProcessClassName": "Solicitud de Contratación",
                "ProcessBaseReference": "-55.1_33",
                "ProcessTheme1": "",
                "ProcessTheme2": "",
                "ProcessTheme3": "",
                "ProcessTheme4": "",
                "ProcessTheme5": "",
                "ProcessTheme6": "",
                "ProcessTheme7": "",
                "ProcessTheme8": "",
                "ProcessTheme9": "",
                "ProcessTheme10": "",
                "TaskClassCode": "TP.6",
                "TaskClassName": "Firma y aprobación solicitud de contratación",
                "ArrivalDate": "2023-11-08T12:36:37.803-06:00",
                "Deadline": "1900-01-01T00:00:00",
                "NoticeDate": "1900-01-01T00:00:00",
                "OriginalStartDatePrevision": "1900-01-01T00:00:00",
                "OriginalEndDatePrevision": "1900-01-01T00:00:00",
                "CurrentStartDatePrevision": "1900-01-01T00:00:00",
                "CurrentEndDatePrevision": "1900-01-01T00:00:00",
                "NameOfStartMessageCreator": "AP1",
                "NatureOfStartMessageCreator": "Empleado",
                "IsReclaimable": false,
                "Project": "SISTEMAS"
            },
            {
                "TaskId": 1574,
                "ProcessId": 3331,
                "StatusName": "Iniciada",
                "ProcessClassName": "Solicitud de Contratación",
                "ProcessBaseReference": "-55.1_34",
                "ProcessTheme1": "",
                "ProcessTheme2": "",
                "ProcessTheme3": "",
                "ProcessTheme4": "",
                "ProcessTheme5": "",
                "ProcessTheme6": "",
                "ProcessTheme7": "",
                "ProcessTheme8": "",
                "ProcessTheme9": "",
                "ProcessTheme10": "",
                "TaskClassCode": "TP.1",
                "TaskClassName": "Gestionar la solicitud de contratación",
                "ArrivalDate": "2023-11-08T16:45:49.1-06:00",
                "Deadline": "1900-01-01T00:00:00",
                "NoticeDate": "1900-01-01T00:00:00",
                "OriginalStartDatePrevision": "1900-01-01T00:00:00",
                "OriginalEndDatePrevision": "1900-01-01T00:00:00",
                "CurrentStartDatePrevision": "1900-01-01T00:00:00",
                "CurrentEndDatePrevision": "1900-01-01T00:00:00",
                "NameOfStartMessageCreator": "AP1",
                "NatureOfStartMessageCreator": "Empleado",
                "IsReclaimable": false,
                "Project": "SISTEMAS"
            },
            {
                "TaskId": 1575,
                "ProcessId": 3348,
                "StatusName": "Iniciada",
                "ProcessClassName": "Solicitud de Contratación",
                "ProcessBaseReference": "-55.1_35",
                "ProcessTheme1": "",
                "ProcessTheme2": "",
                "ProcessTheme3": "",
                "ProcessTheme4": "",
                "ProcessTheme5": "",
                "ProcessTheme6": "",
                "ProcessTheme7": "",
                "ProcessTheme8": "",
                "ProcessTheme9": "",
                "ProcessTheme10": "",
                "TaskClassCode": "TP.1",
                "TaskClassName": "Gestionar la solicitud de contratación",
                "ArrivalDate": "2023-11-09T15:48:04.84-06:00",
                "Deadline": "1900-01-01T00:00:00",
                "NoticeDate": "1900-01-01T00:00:00",
                "OriginalStartDatePrevision": "1900-01-01T00:00:00",
                "OriginalEndDatePrevision": "1900-01-01T00:00:00",
                "CurrentStartDatePrevision": "1900-01-01T00:00:00",
                "CurrentEndDatePrevision": "1900-01-01T00:00:00",
                "NameOfStartMessageCreator": "AP1",
                "NatureOfStartMessageCreator": "Empleado",
                "IsReclaimable": false,
                "Project": "SISTEMAS"
            },
            {
                "TaskId": 1613,
                "ProcessId": 3397,
                "StatusName": "Iniciada",
                "ProcessClassName": "Solicitud de Contratación",
                "ProcessBaseReference": "TIN-55.1_42",
                "ProcessTheme1": "",
                "ProcessTheme2": "",
                "ProcessTheme3": "",
                "ProcessTheme4": "",
                "ProcessTheme5": "",
                "ProcessTheme6": "",
                "ProcessTheme7": "",
                "ProcessTheme8": "",
                "ProcessTheme9": "",
                "ProcessTheme10": "",
                "TaskClassCode": "TP.1",
                "TaskClassName": "Gestionar la solicitud de contratación",
                "ArrivalDate": "2023-11-13T13:21:57.65-06:00",
                "Deadline": "2023-11-16T13:21:57-06:00",
                "NoticeDate": "1900-01-01T00:00:00",
                "OriginalStartDatePrevision": "1900-01-01T00:00:00",
                "OriginalEndDatePrevision": "1900-01-01T00:00:00",
                "CurrentStartDatePrevision": "1900-01-01T00:00:00",
                "CurrentEndDatePrevision": "1900-01-01T00:00:00",
                "NameOfStartMessageCreator": "AP1",
                "NatureOfStartMessageCreator": "Empleado",
                "IsReclaimable": false,
                "Project": "SISTEMAS"
            },
            {
                "TaskId": 1619,
                "ProcessId": 3405,
                "StatusName": "Llegada",
                "ProcessClassName": "Solicitud de Contratación",
                "ProcessBaseReference": "TIN-55.1_45",
                "ProcessTheme1": "SANCHEZ QUIROS GABRIEL",
                "ProcessTheme2": "2023-11-14 13:27:08",
                "ProcessTheme3": "Oficina en el Exterior",
                "ProcessTheme4": "",
                "ProcessTheme5": "",
                "ProcessTheme6": "",
                "ProcessTheme7": "",
                "ProcessTheme8": "",
                "ProcessTheme9": "",
                "ProcessTheme10": "",
                "TaskClassCode": "TP.1",
                "TaskClassName": "Gestionar la solicitud de contratación",
                "ArrivalDate": "2023-11-14T13:27:16.17-06:00",
                "Deadline": "2023-11-15T13:27:16-06:00",
                "NoticeDate": "1900-01-01T00:00:00",
                "OriginalStartDatePrevision": "1900-01-01T00:00:00",
                "OriginalEndDatePrevision": "1900-01-01T00:00:00",
                "CurrentStartDatePrevision": "1900-01-01T00:00:00",
                "CurrentEndDatePrevision": "1900-01-01T00:00:00",
                "NameOfStartMessageCreator": "AP1",
                "NatureOfStartMessageCreator": "Empleado",
                "IsReclaimable": false,
                "Project": "SISTEMAS"
            },
            {
                "TaskId": 1812,
                "ProcessId": 3497,
                "StatusName": "Llegada",
                "ProcessClassName": "Informe de Adjudicación",
                "ProcessBaseReference": "TIN-56.1_15",
                "ProcessTheme1": "",
                "ProcessTheme2": "2023-11-29 10:30:18",
                "ProcessTheme3": "",
                "ProcessTheme4": "",
                "ProcessTheme5": "",
                "ProcessTheme6": "",
                "ProcessTheme7": "",
                "ProcessTheme8": "",
                "ProcessTheme9": "",
                "ProcessTheme10": "",
                "TaskClassCode": "TP.1",
                "TaskClassName": "Seguimiento de Tramites pendientes de tramitar",
                "ArrivalDate": "2023-12-06T14:32:55.47-06:00",
                "Deadline": "2024-12-08T14:32:55-06:00",
                "NoticeDate": "1900-01-01T00:00:00",
                "OriginalStartDatePrevision": "1900-01-01T00:00:00",
                "OriginalEndDatePrevision": "1900-01-01T00:00:00",
                "CurrentStartDatePrevision": "1900-01-01T00:00:00",
                "CurrentEndDatePrevision": "1900-01-01T00:00:00",
                "NameOfStartMessageCreator": "AP1",
                "NatureOfStartMessageCreator": "Empleado",
                "IsReclaimable": false,
                "Project": "SISTEMAS"
            },
            {
                "TaskId": 1703,
                "ProcessId": 3486,
                "StatusName": "Llegada",
                "ProcessClassName": " Módulo SICERE",
                "ProcessBaseReference": "MS-58.1_56",
                "ProcessTheme1": "JC INC LD",
                "ProcessTheme2": "070124024306",
                "ProcessTheme3": "Activación",
                "ProcessTheme4": "",
                "ProcessTheme5": "",
                "ProcessTheme6": "",
                "ProcessTheme7": "",
                "ProcessTheme8": "",
                "ProcessTheme9": "",
                "ProcessTheme10": "",
                "TaskClassCode": "TP.12",
                "TaskClassName": "Firma solicitud",
                "ArrivalDate": "2023-11-28T14:05:53.233-06:00",
                "Deadline": "1900-01-01T00:00:00",
                "NoticeDate": "1900-01-01T00:00:00",
                "OriginalStartDatePrevision": "1900-01-01T00:00:00",
                "OriginalEndDatePrevision": "1900-01-01T00:00:00",
                "CurrentStartDatePrevision": "1900-01-01T00:00:00",
                "CurrentEndDatePrevision": "1900-01-01T00:00:00",
                "NameOfStartMessageCreator": "ApExt",
                "NatureOfStartMessageCreator": "Externo",
                "IsReclaimable": false,
                "Project": "SISTEMAS"
            }
         ]`

         this.tasks.value = await JSON.parse(responseStringVUI)
         this.tasks.value = [...this.tasks.value, ...JSON.parse(responseStringPROCOMER)]
    }

    async fetchTasks():Promise<void>{
        try {
            const URl = 'http://sistemas-des-int.procomer.com/api/v1-beta/PersonalTask/Search'
            const myHeaders = new Headers();
            myHeaders.append("ApiKey", "4nSeGz6lGzuJoWZerxxboa2z69AdnPm1oVTB1MPyMur5kUclzm94VdpqJwLXNbF+onBbnGYtmhxvMTvPcADWFSI0VoL3LyWRLpFz/df5xi+Xd+7wRRw65lnOBFQHqRD9cmYFTK9QExnwCkveX2Why0agLHSS8pLVB+lE2OhW3YasvBMHx69l1XPQfQkIBIg/");
            myHeaders.append("UserData", "De6LWutpTi8=");
            myHeaders.append("Content-Type", "application/json");

            const raw = JSON.stringify({
                "status": "Pending",
                "processClassName": "Solicitud de Contratación"
            });

            const requestOptions = {
                method: 'POST',
                headers: myHeaders,
                body: raw,
            };

            const response = await fetch(URl, requestOptions)
            const data = await response.json()
            this.tasks.value = await data
        } catch (error) {
            console.log(error)
        }
    }
}

export default ApiService